#!/bin/sh

home=/opt/fhem

cd $home

# Start watchdog
sudo -u fhem ./runwatchdog.sh

cnt=`ps -ef | grep "fhem.pl" | grep -v grep | wc -l`
if [ "$cnt" -eq "0" ] ; then
  echo "Starting fhem..."
  sudo -u fhem perl fhem.pl fhem.cfg
else
  echo "fhem is allready running"
fi
